/* SVG helpers: add a question by supplying visual states, then four { id, visual } options. */
const COLORS = { blue: '#4666d8', coral: '#e46f71', mint: '#45ad92', gold: '#d79a36', ink: '#344054' };
function mark({ shape = 'triangle', color = 'blue', rotation = 0, x = 50, y = 50, size = 18, mirror = false, inner = null }) {
  const fill = COLORS[color];
  const transform = `translate(${x} ${y}) rotate(${rotation}) scale(${mirror ? -1 : 1} 1)`;
  const forms = {
    triangle: `<path d="M0 -${size} L${size} ${size} L-${size} ${size} Z"/>`,
    square: `<rect x="-${size}" y="-${size}" width="${size * 2}" height="${size * 2}" rx="3"/>`,
    circle: `<circle r="${size}"/>`,
    arrow: `<path d="M-${size} -${size / 2} H${size / 4} V-${size} L${size} 0 L${size / 4} ${size} V${size / 2} H-${size} Z"/>`,
    diamond: `<path d="M0 -${size} L${size} 0 L0 ${size} L-${size} 0 Z"/>`,
    plus: `<path d="M-${size / 3} -${size} H${size / 3} V-${size / 3} H${size} V${size / 3} H${size / 3} V${size} H-${size / 3} V${size / 3} H-${size} V-${size / 3} H-${size / 3} Z"/>`,
    star: `<path d="M0 -${size} L${size * .24} -${size * .32} L${size} -${size * .3} L${size * .39} ${size * .13} L${size * .62} ${size} L0 ${size * .57} L-${size * .62} ${size} L-${size * .39} ${size * .13} L-${size} -${size * .3} L-${size * .24} -${size * .32} Z"/>`,
    line: `<rect x="-${size}" y="-${Math.max(3, size / 6)}" width="${size * 2}" height="${Math.max(6, size / 3)}" rx="3"/>`
  };
  const innerMark = inner ? mark({ ...inner, x: inner.x ?? 0, y: inner.y ?? 0, size: inner.size ?? size * .34 }) : '';
  return `<g fill="${fill}" transform="${transform}">${forms[shape]}${innerMark}</g>`;
}
function scene(marks) { return `<svg class="visual-svg" viewBox="0 0 100 100" aria-hidden="true">${marks.map(mark).join('')}</svg>`; }
function panel(marks, x, y, size = 72, unknown = false) { return `<g transform="translate(${x} ${y})"><rect class="visual-cell" width="${size}" height="${size}" rx="8"/>${unknown ? `<text class="visual-question" x="${size / 2}" y="${size / 2 + 8}">?</text>` : `<g transform="scale(${size / 100})">${marks.map(mark).join('')}</g>`}</g>`; }
function series(states) { const width = states.length * 96; return `<svg class="visual-svg visual-series" viewBox="0 0 ${width} 84" aria-label="도형 순서 문제">${states.map((item, index) => panel(item, index * 96, 6, 72, item === null)).join('')}</svg>`; }
function matrix(states) { return `<svg class="visual-svg visual-matrix" viewBox="0 0 264 264" aria-label="도형 행렬 문제">${states.map((item, index) => panel(item, (index % 3) * 88, Math.floor(index / 3) * 88, 80, item === null)).join('')}</svg>`; }
function matrix4(states) { return `<svg class="visual-svg visual-matrix" viewBox="0 0 280 280" aria-label="4 곱하기 4 도형 행렬 문제">${states.map((item, index) => panel(item, (index % 4) * 70, Math.floor(index / 4) * 70, 64, item === null)).join('')}</svg>`; }
function options(correct, distractors) { return [correct, ...distractors].map((marks, index) => ({ id: `choice-${index + 1}`, visual: scene(marks) })); }
const TYPE_PLAN = ['회전/방향', '위치 이동', '도형 개수 변화', '대칭', '도형 행렬', '복합 규칙', '도형 겹침', '대칭', '색상 + 도형 변화', '도형 행렬', '색상 + 도형 변화', '위치 이동', '대칭', '도형 겹침', '도형 행렬', '복합 규칙', '도형 개수 변화', '도형 행렬', '도형 겹침', '회전/방향', '도형 행렬', '회전/방향', '위치 이동', '도형 개수 변화', '색상 + 도형 변화', '복합 규칙', '회전/방향', '위치 이동', '도형 개수 변화', '복합 규칙'];
function difficultyFor(id) { const number = Number(id.slice(1)); return number <= 5 ? '중상급' : number <= 12 ? '고급' : number <= 19 ? '매우 고급' : '최상급'; }
function visualQuestion(id, difficulty, category, questionType, questionVisual, correct, distractors, explanation) {
  const allOptions = options(correct, distractors);
  const number = Number(id.slice(1));
  return { id, difficulty: difficultyFor(id), category: TYPE_PLAN[number - 1], questionType: TYPE_PLAN[number - 1], question: '빈칸에 들어갈 도형을 선택하세요.', questionVisual, options: allOptions, answer: 'choice-1', explanation, solutionVisual: allOptions[0].visual };
}

const questions = [
  visualQuestion('v01', '초급', '공간', '회전', series([[{ rotation: 0 }], [{ rotation: 90 }], [{ rotation: 180 }], null]), [{ rotation: 270 }], [[{ rotation: 0 }], [{ rotation: 90, color: 'coral' }], [{ rotation: 180 }]], '① 삼각형은 매 칸 90°씩 시계 방향으로 회전합니다. ② 다음 방향은 아래를 향합니다.'),
  visualQuestion('v02', '초급', '공간', '이동', series([[{ shape: 'circle', x: 22, y: 22 }], [{ shape: 'circle', x: 78, y: 22 }], [{ shape: 'circle', x: 78, y: 78 }], null]), [{ shape: 'circle', x: 22, y: 78 }], [[{ shape: 'circle', x: 22, y: 22 }], [{ shape: 'circle', x: 50, y: 50 }], [{ shape: 'circle', x: 78, y: 78 }]], '① 점은 네 모서리를 시계 방향으로 이동합니다. ② 다음 위치는 왼쪽 아래입니다.'),
  visualQuestion('v03', '초급', '패턴', '개수 변화', series([[{ shape: 'circle', x: 28, y: 50 }], [{ shape: 'circle', x: 28, y: 50 }, { shape: 'circle', x: 72, y: 50 }], [{ shape: 'circle', x: 22, y: 50 }, { shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 78, y: 50 }], null]), [{ shape: 'circle', x: 18, y: 50 }, { shape: 'circle', x: 40, y: 50 }, { shape: 'circle', x: 62, y: 50 }, { shape: 'circle', x: 84, y: 50 }], [[{ shape: 'circle', x: 28, y: 30 }, { shape: 'circle', x: 72, y: 30 }], [{ shape: 'circle', x: 30, y: 30 }, { shape: 'circle', x: 70, y: 30 }, { shape: 'circle', x: 50, y: 70 }], [{ shape: 'circle', x: 50, y: 50 }]], '① 원의 수가 한 개씩 증가합니다. ② 네 개의 원이 가로로 놓인 그림이 정답입니다.'),
  visualQuestion('v04', '초급', '대칭', '좌우 대칭', series([[{ shape: 'arrow', rotation: 0, x: 30, y: 50 }], [{ shape: 'arrow', rotation: 180, x: 70, y: 50 }], [{ shape: 'arrow', rotation: 0, x: 30, y: 50 }], null]), [{ shape: 'arrow', rotation: 180, x: 70, y: 50 }], [[{ shape: 'arrow', rotation: 0, x: 70, y: 50 }], [{ shape: 'arrow', rotation: 180, x: 30, y: 50 }], [{ shape: 'arrow', rotation: 90, x: 70, y: 50 }]], '① 화살표는 좌우로 반사됩니다. ② 위치와 방향이 함께 뒤집힙니다.'),
  visualQuestion('v05', '중급', '행렬', '색상 + 모양', matrix([[{ shape: 'circle', color: 'blue' }], [{ shape: 'triangle', color: 'coral' }], [{ shape: 'square', color: 'mint' }], [{ shape: 'triangle', color: 'coral' }], [{ shape: 'square', color: 'mint' }], [{ shape: 'circle', color: 'blue' }], [{ shape: 'square', color: 'mint' }], [{ shape: 'circle', color: 'blue' }], null]), [{ shape: 'triangle', color: 'coral' }], [[{ shape: 'triangle', color: 'blue' }], [{ shape: 'circle', color: 'coral' }], [{ shape: 'square', color: 'mint' }]], '① 각 행의 모양과 색이 한 칸씩 순환합니다. ② 마지막 칸은 빨간 삼각형입니다.'),
  visualQuestion('v06', '중급', '공간', '이동 + 회전', series([[{ shape: 'arrow', rotation: 0, x: 25, y: 25 }], [{ shape: 'arrow', rotation: 90, x: 75, y: 25 }], [{ shape: 'arrow', rotation: 180, x: 75, y: 75 }], null]), [{ shape: 'arrow', rotation: 270, x: 25, y: 75 }], [[{ shape: 'arrow', rotation: 270, x: 75, y: 25 }], [{ shape: 'arrow', rotation: 180, x: 25, y: 75 }], [{ shape: 'arrow', rotation: 0, x: 25, y: 75 }]], '① 화살표는 모서리를 따라 이동합니다. ② 이동할 때마다 90° 회전하므로 왼쪽 아래에서 위를 향합니다.'),
  visualQuestion('v07', '중급', '추론', '겹침', series([[{ shape: 'circle', color: 'blue', x: 36 }, { shape: 'triangle', color: 'coral', x: 64 }], [{ shape: 'circle', color: 'blue', x: 42 }, { shape: 'triangle', color: 'coral', x: 58 }], [{ shape: 'circle', color: 'blue', x: 48 }, { shape: 'triangle', color: 'coral', x: 52 }], null]), [{ shape: 'circle', color: 'blue', x: 50 }, { shape: 'triangle', color: 'coral', x: 50 }], [[{ shape: 'circle', color: 'blue', x: 52 }, { shape: 'triangle', color: 'coral', x: 48 }], [{ shape: 'circle', color: 'blue', x: 50 }, { shape: 'triangle', color: 'coral', x: 50, rotation: 180 }], [{ shape: 'circle', color: 'blue', x: 42 }, { shape: 'triangle', color: 'coral', x: 58 }]], '① 두 도형의 간격이 일정하게 줄어듭니다. ② 다음 단계에서 두 도형의 중심이 겹칩니다.'),
  visualQuestion('v08', '중급', '대칭', '상하 대칭', matrix([[{ shape: 'arrow', rotation: 0, y: 25 }], [{ shape: 'arrow', rotation: 90, y: 25 }], [{ shape: 'arrow', rotation: 180, y: 25 }], [{ shape: 'arrow', rotation: 180, y: 75 }], [{ shape: 'arrow', rotation: 270, y: 75 }], [{ shape: 'arrow', rotation: 0, y: 75 }], [{ shape: 'arrow', rotation: 0, y: 25 }], [{ shape: 'arrow', rotation: 90, y: 25 }], null]), [{ shape: 'arrow', rotation: 180, y: 25 }], [[{ shape: 'arrow', rotation: 0, y: 75 }], [{ shape: 'arrow', rotation: 180, y: 75 }], [{ shape: 'arrow', rotation: 270, y: 25 }]], '① 위 행은 오른쪽으로 90°씩 회전합니다. ② 가운데 행은 이를 상하 대칭한 모습이며, 마지막 행은 위 행을 반복합니다.'),
  visualQuestion('v09', '중급', '패턴', '크기 + 색상', series([[{ shape: 'diamond', color: 'blue', size: 12 }], [{ shape: 'diamond', color: 'coral', size: 18 }], [{ shape: 'diamond', color: 'blue', size: 24 }], null]), [{ shape: 'diamond', color: 'coral', size: 30 }], [[{ shape: 'diamond', color: 'blue', size: 30 }], [{ shape: 'diamond', color: 'coral', size: 24 }], [{ shape: 'diamond', color: 'mint', size: 30 }]], '① 마름모는 커지고 색은 파랑·빨강으로 번갈아 바뀝니다. ② 다음은 가장 큰 빨간 마름모입니다.'),
  visualQuestion('v10', '중급', '행렬', '개수 + 위치', matrix([[{ shape: 'circle', x: 25, y: 25 }], [{ shape: 'circle', x: 50, y: 50 }], [{ shape: 'circle', x: 75, y: 75 }], [{ shape: 'circle', x: 25, y: 75 }, { shape: 'circle', x: 75, y: 25 }], [{ shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 75, y: 75 }], [{ shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 75, y: 25 }], [{ shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 75, y: 75 }], [{ shape: 'circle', x: 25, y: 75 }, { shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 75, y: 25 }], null]), [{ shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 75, y: 75 }], [[{ shape: 'circle', x: 25, y: 75 }, { shape: 'circle', x: 50, y: 50 }, { shape: 'circle', x: 75, y: 25 }], [{ shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 75, y: 75 }], [{ shape: 'circle', x: 50, y: 50 }]], '① 행마다 원의 수가 1, 2, 3개로 늘어납니다. ② 열의 대각선 위치 순서도 반복됩니다.'),
  visualQuestion('v11', '고급', '행렬', '회전 + 색상', matrix([[{ shape: 'triangle', color: 'blue', rotation: 0 }], [{ shape: 'triangle', color: 'coral', rotation: 90 }], [{ shape: 'triangle', color: 'mint', rotation: 180 }], [{ shape: 'triangle', color: 'coral', rotation: 90 }], [{ shape: 'triangle', color: 'mint', rotation: 180 }], [{ shape: 'triangle', color: 'blue', rotation: 270 }], [{ shape: 'triangle', color: 'mint', rotation: 180 }], [{ shape: 'triangle', color: 'blue', rotation: 270 }], null]), [{ shape: 'triangle', color: 'coral', rotation: 0 }], [[{ shape: 'triangle', color: 'coral', rotation: 270 }], [{ shape: 'triangle', color: 'blue', rotation: 0 }], [{ shape: 'triangle', color: 'mint', rotation: 0 }]], '① 색은 행과 열에서 세 가지가 순환합니다. ② 방향도 90°씩 순환해 마지막은 빨간 위쪽 삼각형입니다.'),
  visualQuestion('v12', '고급', '공간', '이동 + 개수', series([[{ shape: 'circle', x: 25, y: 25 }], [{ shape: 'circle', x: 75, y: 25 }, { shape: 'circle', x: 75, y: 75 }], [{ shape: 'circle', x: 75, y: 75 }, { shape: 'circle', x: 25, y: 75 }, { shape: 'circle', x: 25, y: 25 }], null]), [{ shape: 'circle', x: 25, y: 75 }, { shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 75, y: 25 }, { shape: 'circle', x: 75, y: 75 }], [[{ shape: 'circle', x: 25, y: 25 }, { shape: 'circle', x: 75, y:25 }, { shape: 'circle', x: 75, y:75 }], [{ shape: 'circle', x: 25, y:75 }, { shape: 'circle', x: 75, y:75 }, { shape: 'circle', x: 75, y:25 }, { shape: 'circle', x: 25, y:25 }], [{ shape: 'circle', x:50,y:50 }]], '① 점이 시계 방향으로 하나씩 추가됩니다. ② 네 번째 단계에는 네 모서리가 모두 채워집니다.'),
  visualQuestion('v13', '고급', '대칭', '대칭 + 색상', series([[{ shape: 'arrow', color: 'blue', rotation: 0, x: 25 }, { shape: 'circle', color: 'coral', x: 75 }], [{ shape: 'circle', color: 'coral', x: 25 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 75 }], [{ shape: 'arrow', color: 'blue', rotation: 0, x: 25 }, { shape: 'circle', color: 'coral', x: 75 }], null]), [{ shape: 'circle', color: 'coral', x: 25 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 75 }], [[{ shape: 'circle', color: 'blue', x: 25 }, { shape: 'arrow', color: 'coral', rotation: 180, x: 75 }], [{ shape: 'arrow', color: 'blue', rotation: 0, x: 75 }, { shape: 'circle', color: 'coral', x: 25 }], [{ shape: 'circle', color: 'coral', x: 75 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 25 }]], '① 두 도형은 좌우 자리를 바꿉니다. ② 화살표는 대칭될 때 반대 방향으로 회전합니다.'),
  visualQuestion('v14', '고급', '추론', '겹침 + 회전', series([[{ shape: 'square', color: 'blue', size: 20 }, { shape: 'triangle', color: 'coral', rotation: 0, size: 14 }], [{ shape: 'square', color: 'blue', size: 20 }, { shape: 'triangle', color: 'coral', rotation: 90, size: 14 }], [{ shape: 'square', color: 'blue', size: 20 }, { shape: 'triangle', color: 'coral', rotation: 180, size: 14 }], null]), [{ shape: 'square', color: 'blue', size: 20 }, { shape: 'triangle', color: 'coral', rotation: 270, size: 14 }], [[{ shape: 'square', color: 'blue', size: 20 }, { shape: 'triangle', color: 'coral', rotation: 0, size: 14 }], [{ shape: 'square', color: 'coral', size: 20 }, { shape: 'triangle', color: 'blue', rotation: 270, size: 14 }], [{ shape: 'square', color: 'blue', size: 14 }, { shape: 'triangle', color: 'coral', rotation: 270, size: 20 }]], '① 바깥 사각형은 고정되어 있습니다. ② 겹친 삼각형만 90°씩 회전합니다.'),
  visualQuestion('v15', '고급', '행렬', '모양 + 개수', matrix([[{ shape: 'circle', x: 35 }, { shape: 'circle', x: 65 }], [{ shape: 'triangle', x: 35 }, { shape: 'triangle', x: 65 }], [{ shape: 'square', x: 35 }, { shape: 'square', x: 65 }], [{ shape: 'triangle', y: 35 }, { shape: 'triangle', y: 65 }], [{ shape: 'square', y: 35 }, { shape: 'square', y: 65 }], [{ shape: 'circle', y: 35 }, { shape: 'circle', y: 65 }], [{ shape: 'square', x: 35, y: 35 }, { shape: 'square', x: 65, y: 65 }], [{ shape: 'circle', x: 35, y: 35 }, { shape: 'circle', x: 65, y: 65 }], null]), [{ shape: 'triangle', x: 35, y: 35 }, { shape: 'triangle', x: 65, y: 65 }], [[{ shape: 'triangle', x: 35 }, { shape: 'triangle', x: 65 }], [{ shape: 'square', x: 35, y: 35 }, { shape: 'square', x: 65, y: 65 }], [{ shape: 'triangle', y: 35 }, { shape: 'triangle', y: 65 }]], '① 모양은 행과 열에서 순환합니다. ② 각 행은 배치 방향도 가로·세로·대각선으로 변합니다.'),
  visualQuestion('v16', '고급', '공간', '위치 + 크기 + 회전', series([[{ shape: 'triangle', color: 'mint', x: 25, y: 25, size: 12 }], [{ shape: 'triangle', color: 'mint', x: 75, y: 25, size: 16, rotation: 90 }], [{ shape: 'triangle', color: 'mint', x: 75, y: 75, size: 20, rotation: 180 }], null]), [{ shape: 'triangle', color: 'mint', x: 25, y: 75, size: 24, rotation: 270 }], [[{ shape: 'triangle', color: 'mint', x: 25, y: 75, size: 20, rotation: 270 }], [{ shape: 'triangle', color: 'mint', x: 25, y: 25, size: 24, rotation: 270 }], [{ shape: 'triangle', color: 'mint', x: 25, y: 75, size: 24, rotation: 180 }]], '① 모서리를 따라 이동합니다. ② 동시에 90° 회전하고 크기도 한 단계씩 커집니다.'),
  visualQuestion('v17', '고급', '패턴', '색상 + 개수 + 방향', series([[{ shape: 'arrow', color: 'blue', rotation: 0 }], [{ shape: 'arrow', color: 'coral', rotation: 90, x: 35 }, { shape: 'arrow', color: 'coral', rotation: 90, x: 65 }], [{ shape: 'arrow', color: 'mint', rotation: 180, x: 25 }, { shape: 'arrow', color: 'mint', rotation: 180, x: 50 }, { shape: 'arrow', color: 'mint', rotation: 180, x: 75 }], null]), [{ shape: 'arrow', color: 'blue', rotation: 270, x: 18 }, { shape: 'arrow', color: 'blue', rotation: 270, x: 40 }, { shape: 'arrow', color: 'blue', rotation: 270, x: 62 }, { shape: 'arrow', color: 'blue', rotation: 270, x: 84 }], [[{ shape: 'arrow', color: 'coral', rotation: 270, x: 18 }, { shape: 'arrow', color: 'coral', rotation: 270, x: 40 }, { shape: 'arrow', color: 'coral', rotation: 270, x: 62 }, { shape: 'arrow', color: 'coral', rotation: 270, x: 84 }], [{ shape: 'arrow', color: 'blue', rotation: 180, x: 18 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 40 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 62 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 84 }], [{ shape: 'arrow', color: 'blue', rotation: 270 }]], '① 화살표 수는 1개씩 증가합니다. ② 색은 세 가지 순환, 방향은 90°씩 회전합니다.'),
  visualQuestion('v18', '최상급', '행렬', '행 + 열 복합 규칙', matrix([[{ shape: 'circle', color: 'blue', x: 25 }, { shape: 'triangle', color: 'coral', x: 75, rotation: 0 }], [{ shape: 'triangle', color: 'coral', y: 25, rotation: 90 }, { shape: 'square', color: 'mint', y: 75 }], [{ shape: 'square', color: 'mint', x: 25, y: 25 }, { shape: 'circle', color: 'blue', x: 75, y: 75 }], [{ shape: 'triangle', color: 'coral', x: 25 }, { shape: 'square', color: 'mint', x: 75 }], [{ shape: 'square', color: 'mint', y: 25 }, { shape: 'circle', color: 'blue', y: 75 }], [{ shape: 'circle', color: 'blue', x: 25, y: 25 }, { shape: 'triangle', color: 'coral', x: 75, y: 75, rotation: 180 }], [{ shape: 'square', color: 'mint', x: 25 }, { shape: 'circle', color: 'blue', x: 75 }], [{ shape: 'circle', color: 'blue', y: 25 }, { shape: 'triangle', color: 'coral', y: 75, rotation: 270 }], null]), [{ shape: 'triangle', color: 'coral', x: 25, y: 25, rotation: 0 }, { shape: 'square', color: 'mint', x: 75, y: 75 }], [[{ shape: 'triangle', color: 'coral', x: 25, y: 25, rotation: 180 }, { shape: 'square', color: 'mint', x: 75, y: 75 }], [{ shape: 'circle', color: 'blue', x: 25, y: 25 }, { shape: 'triangle', color: 'coral', x: 75, y: 75 }], [{ shape: 'triangle', color: 'coral', x: 25 }, { shape: 'square', color: 'mint', x: 75 }]], '① 두 도형의 종류와 색은 3개 주기로 순환합니다. ② 배치 방향은 행마다 가로·세로·대각선, 삼각형 방향도 열 규칙을 따릅니다.'),
  visualQuestion('v19', '최상급', '대칭', '대칭 + 겹침 + 이동', matrix([[{ shape: 'arrow', color: 'blue', rotation: 0, x: 30 }, { shape: 'circle', color: 'gold', x: 70 }], [{ shape: 'circle', color: 'gold', x: 30 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 70 }], [{ shape: 'arrow', color: 'blue', rotation: 0, x: 50 }, { shape: 'circle', color: 'gold', x: 50 }], [{ shape: 'circle', color: 'gold', y: 30 }, { shape: 'arrow', color: 'blue', rotation: 90, y: 70 }], [{ shape: 'arrow', color: 'blue', rotation: 270, y: 30 }, { shape: 'circle', color: 'gold', y: 70 }], [{ shape: 'circle', color: 'gold', x: 50 }, { shape: 'arrow', color: 'blue', rotation: 0, x: 50 }], [{ shape: 'arrow', color: 'blue', rotation: 0, x: 30, y: 30 }, { shape: 'circle', color: 'gold', x: 70, y: 70 }], [{ shape: 'circle', color: 'gold', x: 30, y: 30 }, { shape: 'arrow', color: 'blue', rotation: 180, x: 70, y: 70 }], null]), [{ shape: 'arrow', color: 'blue', rotation: 0, x: 50, y: 50 }, { shape: 'circle', color: 'gold', x: 50, y: 50 }], [[{ shape: 'arrow', color: 'blue', rotation: 180, x: 50, y: 50 }, { shape: 'circle', color: 'gold', x: 50, y: 50 }], [{ shape: 'arrow', color: 'blue', rotation: 0, x: 30, y: 30 }, { shape: 'circle', color: 'gold', x: 70, y: 70 }], [{ shape: 'circle', color: 'gold', x: 50, y: 50 }]], '① 각 행의 첫 두 칸은 대칭 쌍입니다. ② 세 번째 칸은 두 도형이 중앙에서 겹친 모습입니다.'),
  visualQuestion('v20', '최상급', '공간', '회전 + 이동 + 색상', series([[{ shape: 'plus', color: 'blue', rotation: 0, x: 25, y: 25 }, { shape: 'triangle', color: 'coral', rotation: 0, x: 75, y: 75 }], [{ shape: 'plus', color: 'coral', rotation: 45, x: 75, y: 25 }, { shape: 'triangle', color: 'mint', rotation: 90, x: 25, y: 75 }], [{ shape: 'plus', color: 'mint', rotation: 90, x: 75, y: 75 }, { shape: 'triangle', color: 'blue', rotation: 180, x: 25, y: 25 }], null]), [{ shape: 'plus', color: 'blue', rotation: 135, x: 25, y: 75 }, { shape: 'triangle', color: 'coral', rotation: 270, x: 75, y: 25 }], [[{ shape: 'plus', color: 'blue', rotation: 135, x: 25, y: 75 }, { shape: 'triangle', color: 'coral', rotation: 180, x: 75, y: 25 }], [{ shape: 'plus', color: 'coral', rotation: 135, x: 25, y: 75 }, { shape: 'triangle', color: 'blue', rotation: 270, x: 75, y: 25 }], [{ shape: 'plus', color: 'blue', rotation: 90, x: 25, y: 75 }, { shape: 'triangle', color: 'coral', rotation: 270, x: 75, y: 25 }]], '① 두 도형은 반대 모서리를 따라 이동합니다. ② 색은 세 단계 순환하고, 각각 45°와 90°씩 회전합니다.'),
  visualQuestion('v21', '최상급', '행렬', '4방향 행렬', matrix([[{ shape: 'star', color: 'gold', x: 25, y: 25 }], [{ shape: 'star', color: 'gold', x: 75, y: 25 }], [{ shape: 'star', color: 'gold', x: 75, y: 75 }], [{ shape: 'diamond', color: 'blue', x: 25, y: 25 }], [{ shape: 'diamond', color: 'blue', x: 75, y: 25 }], [{ shape: 'diamond', color: 'blue', x: 75, y: 75 }], [{ shape: 'plus', color: 'mint', x: 25, y: 25 }], [{ shape: 'plus', color: 'mint', x: 75, y: 25 }], null]), [{ shape: 'plus', color: 'mint', x: 75, y: 75 }], [[{ shape: 'plus', color: 'mint', x: 25, y: 75 }], [{ shape: 'diamond', color: 'blue', x: 75, y: 75 }], [{ shape: 'plus', color: 'gold', x: 75, y: 75 }]], '① 각 행은 같은 도형과 색을 유지합니다. ② 각 열은 왼쪽 위, 오른쪽 위, 오른쪽 아래 순서로 이동합니다.'),
  visualQuestion('v22', '최상급', '공간', '45도 회전', series([[{ shape: 'line', color: 'ink', rotation: 0 }], [{ shape: 'line', color: 'ink', rotation: 45 }], [{ shape: 'line', color: 'ink', rotation: 90 }], null]), [{ shape: 'line', color: 'ink', rotation: 135 }], [[{ shape: 'line', color: 'ink', rotation: 180 }], [{ shape: 'line', color: 'ink', rotation: 90 }], [{ shape: 'line', color: 'coral', rotation: 135 }]], '① 선은 매 단계 45°씩 기울어집니다. ② 다음 선은 135° 방향입니다.'),
  visualQuestion('v23', '최상급', '공간', '세로 이동', series([[{ shape: 'square', color: 'blue', x: 50, y: 18 }], [{ shape: 'square', color: 'blue', x: 50, y: 42 }], [{ shape: 'square', color: 'blue', x: 50, y: 66 }], null]), [{ shape: 'square', color: 'blue', x: 50, y: 88 }], [[{ shape: 'square', color: 'blue', x: 18, y: 88 }], [{ shape: 'square', color: 'blue', x: 50, y: 66 }], [{ shape: 'square', color: 'coral', x: 50, y: 88 }]], '① 사각형은 같은 세로선 위에서 아래로 일정하게 이동합니다. ② 다음 위치는 맨 아래입니다.'),
  visualQuestion('v24', '최상급', '패턴', '감소하는 선', series([[{ shape: 'line', color: 'coral', y: 22 }, { shape: 'line', color: 'coral', y: 42 }, { shape: 'line', color: 'coral', y: 62 }, { shape: 'line', color: 'coral', y: 82 }], [{ shape: 'line', color: 'coral', y: 28 }, { shape: 'line', color: 'coral', y: 50 }, { shape: 'line', color: 'coral', y: 72 }], [{ shape: 'line', color: 'coral', y: 35 }, { shape: 'line', color: 'coral', y: 65 }], null]), [{ shape: 'line', color: 'coral', y: 50 }], [[{ shape: 'line', color: 'coral', y: 35 }, { shape: 'line', color: 'coral', y: 65 }], [{ shape: 'line', color: 'coral', y: 28 }, { shape: 'line', color: 'coral', y: 50 }, { shape: 'line', color: 'coral', y: 72 }], [{ shape: 'line', color: 'blue', y: 50 }]], '① 가로선의 수가 한 개씩 줄어듭니다. ② 하나의 중앙선이 남습니다.'),
  visualQuestion('v25', '최상급', '패턴', '색상 + 모양 순환', series([[{ shape: 'circle', color: 'blue' }], [{ shape: 'square', color: 'coral' }], [{ shape: 'star', color: 'mint' }], null]), [{ shape: 'circle', color: 'blue', rotation: 45 }], [[{ shape: 'circle', color: 'coral' }], [{ shape: 'square', color: 'blue' }], [{ shape: 'star', color: 'mint' }]], '① 모양과 색상이 각각 세 단계 주기로 순환합니다. ② 다음은 파란 원입니다.'),
  visualQuestion('v26', '최상급', '공간', '대칭 + 회전', series([[{ shape: 'arrow', color: 'gold', rotation: 45, x: 25, y: 25 }], [{ shape: 'arrow', color: 'gold', rotation: 135, x: 75, y: 25 }], [{ shape: 'arrow', color: 'gold', rotation: 225, x: 75, y: 75 }], null]), [{ shape: 'arrow', color: 'gold', rotation: 315, x: 25, y: 75 }], [[{ shape: 'arrow', color: 'gold', rotation: 45, x: 25, y: 75 }], [{ shape: 'arrow', color: 'gold', rotation: 315, x: 25, y: 75 }], [{ shape: 'arrow', color: 'gold', rotation: 225, x: 25, y: 75 }]], '① 화살표는 모서리를 순환합니다. ② 위치 이동과 90° 회전이 동시에 일어납니다.'),
  visualQuestion('v27', '최상급', '공간', '180도 회전', series([[{ shape: 'star', color: 'coral', rotation: 0 }], [{ shape: 'star', color: 'coral', rotation: 180 }], [{ shape: 'star', color: 'coral', rotation: 0 }], null]), [{ shape: 'star', color: 'coral', rotation: 180 }], [[{ shape: 'star', color: 'coral', rotation: 90 }], [{ shape: 'star', color: 'blue', rotation: 180 }], [{ shape: 'star', color: 'coral', rotation: 0 }]], '① 별은 매 단계 반 바퀴씩 회전합니다. ② 다음은 180° 회전한 별입니다.'),
  visualQuestion('v28', '최상급', '공간', '대각선 이동', series([[{ shape: 'diamond', color: 'mint', x: 20, y: 20 }], [{ shape: 'diamond', color: 'mint', x: 40, y: 40 }], [{ shape: 'diamond', color: 'mint', x: 60, y: 60 }], null]), [{ shape: 'diamond', color: 'mint', x: 80, y: 80 }], [[{ shape: 'diamond', color: 'mint', x: 80, y: 20 }], [{ shape: 'diamond', color: 'mint', x: 60, y: 60 }], [{ shape: 'diamond', color: 'mint', x: 80, y: 80, rotation: 45 }]], '① 마름모가 왼쪽 위에서 오른쪽 아래로 대각선 이동합니다. ② 다음 위치는 오른쪽 아래입니다.'),
  visualQuestion('v29', '최상급', '패턴', '삼각형 개수 변화', series([[{ shape: 'triangle', color: 'blue', x: 20 }, { shape: 'triangle', color: 'blue', x: 40 }, { shape: 'triangle', color: 'blue', x: 60 }, { shape: 'triangle', color: 'blue', x: 80 }], [{ shape: 'triangle', color: 'blue', x: 28 }, { shape: 'triangle', color: 'blue', x: 50 }, { shape: 'triangle', color: 'blue', x: 72 }], [{ shape: 'triangle', color: 'blue', x: 35 }, { shape: 'triangle', color: 'blue', x: 65 }], null]), [{ shape: 'triangle', color: 'blue', x: 50 }], [[{ shape: 'triangle', color: 'blue', x: 35 }, { shape: 'triangle', color: 'blue', x: 65 }], [{ shape: 'triangle', color: 'blue', x: 28 }, { shape: 'triangle', color: 'blue', x: 50 }, { shape: 'triangle', color: 'blue', x: 72 }], [{ shape: 'triangle', color: 'coral', x: 50 }]], '① 삼각형의 수가 한 개씩 감소합니다. ② 마지막에는 중앙의 삼각형 하나만 남습니다.'),
  visualQuestion('v30', '최상급', '행렬', '행 + 열 + 색상', matrix([[{ shape: 'circle', color: 'blue', x: 25 }, { shape: 'circle', color: 'blue', x: 75 }], [{ shape: 'triangle', color: 'coral', y: 25 }, { shape: 'triangle', color: 'coral', y: 75 }], [{ shape: 'square', color: 'mint', x: 25, y: 25 }, { shape: 'square', color: 'mint', x: 75, y: 75 }], [{ shape: 'triangle', color: 'coral', x: 25 }, { shape: 'triangle', color: 'coral', x: 75 }], [{ shape: 'square', color: 'mint', y: 25 }, { shape: 'square', color: 'mint', y: 75 }], [{ shape: 'circle', color: 'blue', x: 25, y: 25 }, { shape: 'circle', color: 'blue', x: 75, y: 75 }], [{ shape: 'square', color: 'mint', x: 25 }, { shape: 'square', color: 'mint', x: 75 }], [{ shape: 'circle', color: 'blue', y: 25 }, { shape: 'circle', color: 'blue', y: 75 }], null]), [{ shape: 'triangle', color: 'coral', x: 25, y: 25 }, { shape: 'triangle', color: 'coral', x: 75, y: 75 }], [[{ shape: 'triangle', color: 'coral', x: 25 }, { shape: 'triangle', color: 'coral', x: 75 }], [{ shape: 'square', color: 'mint', x: 25, y: 25 }, { shape: 'square', color: 'mint', x: 75, y: 75 }], [{ shape: 'triangle', color: 'blue', x: 25, y: 25 }, { shape: 'triangle', color: 'blue', x: 75, y: 75 }]], '① 모양·색상은 행과 열에서 순환합니다. ② 배치 방향도 가로·세로·대각선으로 바뀌므로 마지막은 빨간 대각선 삼각형입니다.')
];

/* The final six puzzles require at least three simultaneous visual rules. */
function token(shape, innerShape, config = {}) {
  const { innerColor = 'gold', innerRotation = 0, innerSize = 6, ...outer } = config;
  return { shape, ...outer, inner: { shape: innerShape, color: innerColor, rotation: innerRotation, size: innerSize } };
}
function gridToken(row, column, alternate = false) {
  const colors = alternate ? ['mint', 'gold', 'blue', 'coral'] : ['blue', 'coral', 'mint', 'gold'];
  return token(row % 2 ? 'square' : 'triangle', 'arrow', {
    color: colors[(row + column) % 4], rotation: (row * 90 + column * 45) % 360,
    innerColor: colors[(row + column * 2) % 4], innerRotation: (column * 90 - row * 45 + 360) % 360, innerSize: 5
  });
}
function gridVisual(alternate = false) {
  return matrix4(Array.from({ length: 16 }, (_, index) => index === 15 ? null : [gridToken(Math.floor(index / 4), index % 4, alternate)]));
}

questions.splice(24, 6,
  visualQuestion('v25', '최상급', '색상 + 도형 변화', '4×4 행렬', gridVisual(), [gridToken(3, 3)], [[gridToken(3, 3, true)], [token('square', 'arrow', { color: 'mint', rotation: 225, innerColor: 'gold', innerRotation: 135, innerSize: 5 })], [token('triangle', 'arrow', { color: 'mint', rotation: 225, innerColor: 'gold', innerRotation: 90, innerSize: 5 })]], '행은 바깥 도형·회전을, 열은 색과 내부 화살표 방향을 함께 결정합니다.'),
  visualQuestion('v26', '최상급', '복합 규칙', '4×4 홀짝 행렬', matrix4(Array.from({ length: 16 }, (_, index) => {
    if (index === 15) return null;
    const row = Math.floor(index / 4); const column = index % 4;
    return [token((row + column) % 2 ? 'diamond' : 'star', 'line', { color: ['gold', 'blue', 'coral', 'mint'][(row * 2 + column) % 4], rotation: row * 45 + column * 90, innerColor: (row + column) % 2 ? 'mint' : 'ink', innerRotation: (row % 2 ? -45 : 45) * column, innerSize: 5 })];
  })), [token('diamond', 'line', { color: 'blue', rotation: 135, innerColor: 'mint', innerRotation: -135, innerSize: 5 })], [[token('star', 'line', { color: 'blue', rotation: 135, innerColor: 'mint', innerRotation: -135, innerSize: 5 })], [token('diamond', 'line', { color: 'mint', rotation: 135, innerColor: 'mint', innerRotation: -135, innerSize: 5 })], [token('diamond', 'line', { color: 'blue', rotation: 90, innerColor: 'mint', innerRotation: -135, innerSize: 5 })]], '행의 홀짝은 바깥 도형과 내부선 회전 방향을, 열은 색과 각도를 결정합니다.'),
  visualQuestion('v27', '최상급', '회전/방향', '홀수·짝수 작업 기억', series([[token('triangle', 'arrow', { color: 'blue', rotation: 0, x: 22, y: 25, innerColor: 'gold', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'coral', rotation: 90, x: 78, y: 25, innerColor: 'mint', innerRotation: 180 })], [token('triangle', 'arrow', { color: 'mint', rotation: 180, x: 22, y: 75, innerColor: 'gold', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'gold', rotation: 270, x: 78, y: 75, innerColor: 'mint', innerRotation: 180 })], null]), [token('triangle', 'arrow', { color: 'blue', rotation: 0, x: 22, y: 25, innerColor: 'gold', innerRotation: 0 })], [[token('triangle', 'arrow', { color: 'blue', rotation: 0, x: 22, y: 25, innerColor: 'mint', innerRotation: 180 })], [token('triangle', 'arrow', { color: 'blue', rotation: 180, x: 22, y: 25, innerColor: 'gold', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'coral', rotation: 0, x: 22, y: 25, innerColor: 'gold', innerRotation: 0 })]], '홀수와 짝수 단계의 내부 규칙이 다르고, 외부 도형은 위치·색·방향을 동시에 순환합니다.'),
  visualQuestion('v28', '최상급', '위치 이동', '대칭 + 지그재그', series([[token('square', 'circle', { color: 'blue', x: 20, y: 25, innerColor: 'gold' })], [token('square', 'circle', { color: 'coral', x: 80, y: 25, mirror: true, innerColor: 'mint' })], [token('square', 'circle', { color: 'mint', x: 80, y: 75, innerColor: 'gold' })], [token('square', 'circle', { color: 'gold', x: 20, y: 75, mirror: true, innerColor: 'mint' })], null]), [token('square', 'circle', { color: 'blue', x: 50, y: 50, innerColor: 'gold' })], [[token('square', 'circle', { color: 'blue', x: 20, y: 25, innerColor: 'gold' })], [token('square', 'circle', { color: 'blue', x: 50, y: 50, mirror: true, innerColor: 'gold' })], [token('square', 'circle', { color: 'coral', x: 50, y: 50, innerColor: 'gold' })]], '바깥 사각형은 지그재그로 중앙에 모이고, 색·대칭·내부 점 색은 각각 다른 주기입니다.'),
  visualQuestion('v29', '최상급', '도형 개수 변화', '겹침 변환', series([[token('circle', 'triangle', { color: 'blue', x: 28, innerColor: 'coral', innerRotation: 0 }), token('circle', 'triangle', { color: 'blue', x: 72, innerColor: 'coral', innerRotation: 180 })], [token('circle', 'triangle', { color: 'coral', x: 38, innerColor: 'mint', innerRotation: 45 }), token('circle', 'triangle', { color: 'coral', x: 62, innerColor: 'mint', innerRotation: 225 })], [token('circle', 'triangle', { color: 'mint', x: 50, innerColor: 'gold', innerRotation: 90 }), token('circle', 'triangle', { color: 'mint', x: 50, innerColor: 'gold', innerRotation: 270 })], [token('diamond', 'line', { color: 'gold', x: 50, innerColor: 'ink', innerRotation: 0 })], null]), [token('diamond', 'line', { color: 'blue', x: 50, innerColor: 'ink', innerRotation: 90 })], [[token('diamond', 'line', { color: 'gold', x: 50, innerColor: 'ink', innerRotation: 90 })], [token('circle', 'triangle', { color: 'blue', x: 50, innerColor: 'coral' })], [token('diamond', 'line', { color: 'blue', x: 50, innerColor: 'ink', innerRotation: 0 })]], '두 원의 거리·색·내부 삼각형이 함께 변하고, 겹친 뒤에는 새로운 마름모와 내부선 규칙으로 전환됩니다.'),
  visualQuestion('v30', '최상급', '복합 규칙', '4×4 행·열·내부 규칙', matrix4(Array.from({ length: 16 }, (_, index) => {
    if (index === 15) return null;
    const row = Math.floor(index / 4); const column = index % 4; const positions = [[25, 25], [75, 25], [75, 75], [25, 75]]; const [x, y] = positions[(row + column) % 4];
    return [token(['circle', 'triangle', 'square', 'diamond'][row], 'arrow', { color: ['blue', 'coral', 'mint', 'gold'][column], x, y, rotation: row * 45 + column * 90, innerColor: ['gold', 'mint', 'blue', 'coral'][row], innerRotation: column * 90 - row * 45, innerSize: 5 })];
  })), [token('diamond', 'arrow', { color: 'gold', x: 75, y: 75, rotation: 405, innerColor: 'coral', innerRotation: 135, innerSize: 5 })], [[token('diamond', 'arrow', { color: 'gold', x: 25, y: 75, rotation: 405, innerColor: 'coral', innerRotation: 135, innerSize: 5 })], [token('diamond', 'arrow', { color: 'coral', x: 75, y: 75, rotation: 405, innerColor: 'coral', innerRotation: 135, innerSize: 5 })], [token('diamond', 'arrow', { color: 'gold', x: 75, y: 75, rotation: 315, innerColor: 'coral', innerRotation: 135, innerSize: 5 })]], '행은 바깥 모양과 내부 색을, 열은 바깥 색과 내부 방향을 정합니다. 대각선 위치와 회전까지 함께 추론해야 합니다.')
);

questions.splice(0, 5,
  visualQuestion('v01', '중급', '회전/방향', '회전 + 내부 방향 + 색상', series([[token('triangle', 'arrow', { color: 'blue', rotation: 0, innerColor: 'gold', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'coral', rotation: 90, innerColor: 'mint', innerRotation: 270 })], [token('triangle', 'arrow', { color: 'mint', rotation: 180, innerColor: 'gold', innerRotation: 180 })], null]), [token('triangle', 'arrow', { color: 'blue', rotation: 270, innerColor: 'mint', innerRotation: 90 })], [[token('triangle', 'arrow', { color: 'blue', rotation: 270, innerColor: 'mint', innerRotation: 270 })], [token('triangle', 'arrow', { color: 'blue', rotation: 180, innerColor: 'mint', innerRotation: 90 })], [token('triangle', 'arrow', { color: 'mint', rotation: 270, innerColor: 'mint', innerRotation: 90 })]], '바깥 삼각형과 내부 화살표는 반대 방향으로 회전하며, 두 색상은 서로 다른 주기로 바뀝니다.'),
  visualQuestion('v02', '중급', '위치 이동', '시계 이동 + 크기 + 내부 점', series([[token('circle', 'circle', { color: 'blue', x: 22, y: 22, size: 20, innerColor: 'gold', innerSize: 5 })], [token('circle', 'circle', { color: 'coral', x: 78, y: 22, size: 17, innerColor: 'mint', innerSize: 7 })], [token('circle', 'circle', { color: 'mint', x: 78, y: 78, size: 14, innerColor: 'gold', innerSize: 5 })], null]), [token('circle', 'circle', { color: 'blue', x: 22, y: 78, size: 11, innerColor: 'mint', innerSize: 7 })], [[token('circle', 'circle', { color: 'blue', x: 22, y: 78, size: 14, innerColor: 'mint', innerSize: 7 })], [token('circle', 'circle', { color: 'blue', x: 22, y: 22, size: 11, innerColor: 'mint', innerSize: 7 })], [token('circle', 'circle', { color: 'coral', x: 22, y: 78, size: 11, innerColor: 'mint', innerSize: 7 })]], '원은 시계 방향 모서리를 따라 이동하면서 작아지고, 바깥색과 내부 점 색은 교차 순환합니다.'),
  visualQuestion('v03', '중급', '도형 개수 변화', '개수 + 위치 + 색상', series([[token('square', 'line', { color: 'blue', x: 25, y: 25, innerColor: 'gold', innerRotation: 0 })], [token('square', 'line', { color: 'coral', x: 75, y: 25, innerColor: 'mint', innerRotation: 90 }), token('square', 'line', { color: 'coral', x: 75, y: 75, innerColor: 'mint', innerRotation: 90 })], [token('square', 'line', { color: 'mint', x: 75, y: 75, innerColor: 'gold', innerRotation: 180 }), token('square', 'line', { color: 'mint', x: 25, y: 75, innerColor: 'gold', innerRotation: 180 }), token('square', 'line', { color: 'mint', x: 25, y: 25, innerColor: 'gold', innerRotation: 180 })], null]), [token('square', 'line', { color: 'blue', x: 25, y: 75, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 25, y: 25, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 25, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 75, innerColor: 'mint', innerRotation: 270 })], [[token('square', 'line', { color: 'blue', x: 25, y: 75, innerColor: 'gold', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 25, y: 25, innerColor: 'gold', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 25, innerColor: 'gold', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 75, innerColor: 'gold', innerRotation: 270 })], [token('square', 'line', { color: 'blue', x: 25, y: 25, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 25, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 75, y: 75, innerColor: 'mint', innerRotation: 270 }), token('square', 'line', { color: 'blue', x: 25, y: 75, innerColor: 'mint', innerRotation: 270 })], [token('square', 'line', { color: 'mint', x: 25, y: 75, innerColor: 'mint', innerRotation: 270 })]], '도형 수가 하나씩 늘고, 새 도형은 시계 방향 위치를 채웁니다. 색과 내부선도 단계별로 변합니다.'),
  visualQuestion('v04', '중급', '대칭', '대칭 + 회전 + 내부 도형', series([[token('arrow', 'triangle', { color: 'blue', x: 25, rotation: 0, innerColor: 'gold', innerRotation: 0 })], [token('arrow', 'triangle', { color: 'coral', x: 75, rotation: 180, mirror: true, innerColor: 'mint', innerRotation: 180 })], [token('arrow', 'triangle', { color: 'mint', x: 25, rotation: 90, innerColor: 'gold', innerRotation: 270 })], null]), [token('arrow', 'triangle', { color: 'blue', x: 75, rotation: 270, mirror: true, innerColor: 'mint', innerRotation: 90 })], [[token('arrow', 'triangle', { color: 'blue', x: 75, rotation: 270, innerColor: 'mint', innerRotation: 90 })], [token('arrow', 'triangle', { color: 'blue', x: 25, rotation: 270, mirror: true, innerColor: 'mint', innerRotation: 90 })], [token('arrow', 'triangle', { color: 'coral', x: 75, rotation: 270, mirror: true, innerColor: 'mint', innerRotation: 90 })]], '좌우 대칭과 90° 회전이 번갈아 적용되며, 바깥색과 내부 삼각형 방향도 각각 순환합니다.'),
  visualQuestion('v05', '중급', '도형 행렬', '3×3 행·열 복합', matrix([[token('circle', 'arrow', { color: 'blue', rotation: 0, innerColor: 'gold', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'coral', rotation: 45, innerColor: 'mint', innerRotation: 90 })], [token('square', 'arrow', { color: 'mint', rotation: 90, innerColor: 'gold', innerRotation: 180 })], [token('triangle', 'arrow', { color: 'coral', rotation: 90, innerColor: 'mint', innerRotation: 270 })], [token('square', 'arrow', { color: 'mint', rotation: 135, innerColor: 'gold', innerRotation: 0 })], [token('circle', 'arrow', { color: 'blue', rotation: 180, innerColor: 'mint', innerRotation: 90 })], [token('square', 'arrow', { color: 'mint', rotation: 180, innerColor: 'gold', innerRotation: 180 })], [token('circle', 'arrow', { color: 'blue', rotation: 225, innerColor: 'mint', innerRotation: 270 })], null]), [token('triangle', 'arrow', { color: 'coral', rotation: 270, innerColor: 'gold', innerRotation: 0 })], [[token('triangle', 'arrow', { color: 'coral', rotation: 270, innerColor: 'mint', innerRotation: 0 })], [token('triangle', 'arrow', { color: 'coral', rotation: 225, innerColor: 'gold', innerRotation: 0 })], [token('circle', 'arrow', { color: 'coral', rotation: 270, innerColor: 'gold', innerRotation: 0 })]], '행과 열에서 바깥 모양·색이 순환하고, 바깥 회전과 내부 화살표 방향은 서로 다른 증가량을 따릅니다.')
);

// Remove the former 20th-24th source entries so v25-v30 become the final six questions.
questions.splice(19, 5);